"""empty message

Revision ID: 057792e3ba77
Revises: bead29c0348f

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057792e3ba77'
down_revision = 'bead29c0348f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checker_results', sa.Column('finished', sa.TIMESTAMP(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checker_results', 'finished')
    # ### end Alembic commands ###
