"""empty message

Revision ID: 0e400cc111e2
Revises: b216b27a5b41

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e400cc111e2'
down_revision = 'b216b27a5b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('checker_subprocess', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'checker_subprocess')
    # ### end Alembic commands ###
