"""empty message

Revision ID: 10a5ee20d0ef
Revises: fd06fc8ae2cb

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a5ee20d0ef'
down_revision = 'fd06fc8ae2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_traffic_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('team_id', sa.SmallInteger(), nullable=False),
    sa.Column('down_teams_packets', sa.BigInteger(), nullable=False),
    sa.Column('down_teams_bytes', sa.BigInteger(), nullable=False),
    sa.Column('down_teams_syns', sa.BigInteger(), nullable=False),
    sa.Column('down_teams_syn_acks', sa.BigInteger(), nullable=False),
    sa.Column('down_game_packets', sa.BigInteger(), nullable=False),
    sa.Column('down_game_bytes', sa.BigInteger(), nullable=False),
    sa.Column('down_game_syns', sa.BigInteger(), nullable=False),
    sa.Column('down_game_syn_acks', sa.BigInteger(), nullable=False),
    sa.Column('up_teams_packets', sa.BigInteger(), nullable=False),
    sa.Column('up_teams_bytes', sa.BigInteger(), nullable=False),
    sa.Column('up_teams_syns', sa.BigInteger(), nullable=False),
    sa.Column('up_teams_syn_acks', sa.BigInteger(), nullable=False),
    sa.Column('up_game_packets', sa.BigInteger(), nullable=False),
    sa.Column('up_game_bytes', sa.BigInteger(), nullable=False),
    sa.Column('up_game_syns', sa.BigInteger(), nullable=False),
    sa.Column('up_game_syn_acks', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_traffic_stats')
    # ### end Alembic commands ###
