"""empty message

Revision ID: 1418f098d06f
Revises: 65b6acc8e745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1418f098d06f'
down_revision = '65b6acc8e745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checker_files_file_hash'), 'checker_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_checker_filesystem_package'), 'checker_filesystem', ['package'], unique=False)
    op.create_index(op.f('ix_checker_results_status'), 'checker_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checker_results_status'), table_name='checker_results')
    op.drop_index(op.f('ix_checker_filesystem_package'), table_name='checker_filesystem')
    op.drop_index(op.f('ix_checker_files_file_hash'), table_name='checker_files')
    # ### end Alembic commands ###
