"""empty message

Revision ID: 1eeeeb5988b0
Revises: 10a5ee20d0ef

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeeeb5988b0'
down_revision = '10a5ee20d0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_traffic_stats_time'), 'team_traffic_stats', ['time'], unique=False)
    op.create_unique_constraint('team_traffic_stats_unique_1', 'team_traffic_stats', ['time', 'team_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_traffic_stats_unique_1', 'team_traffic_stats', type_='unique')
    op.drop_index(op.f('ix_team_traffic_stats_time'), table_name='team_traffic_stats')
    # ### end Alembic commands ###
