"""empty message

Revision ID: 28250d12516f
Revises: 4225a3d6edbd
Create Date: 2020-06-22 20:47:59.961361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28250d12516f'
down_revision = '4225a3d6edbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('vpn_connection_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'vpn_connection_count')
    # ### end Alembic commands ###
