"""empty message

Revision ID: 2f793eb41f0e
Revises: 4a67c6f412ac

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f793eb41f0e'
down_revision = '4a67c6f412ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checker_results', sa.Column('run_over_time', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checker_results', 'run_over_time')
    # ### end Alembic commands ###
