"""enochecker

Revision ID: 50067ab5c83d
Revises: d2f5aba10faa
Create Date: 2025-05-03 15:43:25.379961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50067ab5c83d'
down_revision = 'd2f5aba10faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checker_results', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True))
    op.drop_column('checker_results', 'stored')
    op.drop_column('checker_results', 'retrieved')
    op.drop_column('checker_results', 'integrity')
    op.add_column('services', sa.Column('checker_runner', sa.String(), server_default=sa.text("''"), nullable=False))
    op.add_column('services', sa.Column('runner_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submitted_flags', 'tick_submitted',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('services', 'runner_config')
    op.drop_column('services', 'checker_runner')
    op.add_column('checker_results', sa.Column('integrity', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('checker_results', sa.Column('retrieved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('checker_results', sa.Column('stored', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('checker_results', 'data')
    # ### end Alembic commands ###
