"""Add ports to service table

Revision ID: 5950403ab77d
Revises: 6a3f046884d6
Create Date: 2024-11-11 14:33:40.895218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5950403ab77d'
down_revision = '6a3f046884d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('ports', sa.String(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'ports')
    # ### end Alembic commands ###
