"""empty message

Revision ID: 5e6a03306c6e
Revises: 86dd27c83676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6a03306c6e'
down_revision = '86dd27c83676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submitted_flags_round_submitted'), 'submitted_flags', ['round_submitted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_flags_round_submitted'), table_name='submitted_flags')
    # ### end Alembic commands ###
