"""empty message

Revision ID: 6417a3f49101
Revises: aea68a3e74a8

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6417a3f49101'
down_revision = 'aea68a3e74a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_flags', sa.Column('is_firstblood', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.create_index(op.f('ix_submitted_flags_is_firstblood'), 'submitted_flags', ['is_firstblood'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_flags_is_firstblood'), table_name='submitted_flags')
    op.drop_column('submitted_flags', 'is_firstblood')
    # ### end Alembic commands ###
