"""empty message

Revision ID: 65b6acc8e745
Revises: a2e99d5c2195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b6acc8e745'
down_revision = 'a2e99d5c2195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_points_round'), 'team_points', ['round'], unique=False)
    op.create_index(op.f('ix_team_rankings_round'), 'team_rankings', ['round'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_rankings_round'), table_name='team_rankings')
    op.drop_index(op.f('ix_team_points_round'), table_name='team_points')
    # ### end Alembic commands ###
