"""empty message

Revision ID: 7aab1b106d02
Revises: e50efd6bd399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aab1b106d02'
down_revision = 'e50efd6bd399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('flag_ids', sa.String(length=128), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'flag_ids')
    # ### end Alembic commands ###
