"""empty message

Revision ID: 86dd27c83676
Revises: 1418f098d06f

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dd27c83676'
down_revision = '1418f098d06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE submitted_flags RENAME round TO round_submitted')
    # op.execute('ALTER INDEX IF EXISTS ix_submitted_flags_round RENAME TO ix_submitted_flags_round_submitted')
    op.execute('DROP INDEX IF EXISTS ix_submitted_flags_round')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE submitted_flags RENAME round_submitted TO round')
    op.execute('ALTER INDEX IF EXISTS ix_submitted_flags_round_submitted RENAME TO ix_submitted_flags_round')
    # ### end Alembic commands ###
