"""Add wireguard status to teams

Revision ID: 922cc6992093
Revises: 5950403ab77d
Create Date: 2024-11-24 00:54:52.897263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922cc6992093'
down_revision = '5950403ab77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('wg_vulnbox_connected', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('teams', sa.Column('wg_boxes_connected', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'wg_boxes_connected')
    op.drop_column('teams', 'wg_vulnbox_connected')
    # ### end Alembic commands ###
