"""empty message

Revision ID: 9676f8be1930
Revises: c84ad4bd6649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9676f8be1930'
down_revision = 'c84ad4bd6649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submitted_flags_unique_1', 'submitted_flags', type_='unique')
    op.create_unique_constraint('submitted_flags_unique_1', 'submitted_flags', ['submitted_by', 'team_id', 'service_id', 'expires', 'payload'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submitted_flags_unique_1', 'submitted_flags', type_='unique')
    op.create_unique_constraint('submitted_flags_unique_1', 'submitted_flags', ['submitted_by', 'team_id', 'service_id', 'expires'])
    # ### end Alembic commands ###
