"""empty message

Revision ID: a2e99d5c2195
Revises: 9676f8be1930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e99d5c2195'
down_revision = '9676f8be1930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_checker_results_round'), 'checker_results', ['round'], unique=False)
    op.create_index(op.f('ix_submitted_flags_round'), 'submitted_flags', ['round'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_flags_round'), table_name='submitted_flags')
    op.drop_index(op.f('ix_checker_results_round'), table_name='checker_results')
    # ### end Alembic commands ###
