"""empty message

Revision ID: aea68a3e74a8
Revises: 1eeeeb5988b0

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea68a3e74a8'
down_revision = '1eeeeb5988b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('num_payloads', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'num_payloads')
    # ### end Alembic commands ###
