"""empty message

Revision ID: b216b27a5b41
Revises: 5e6a03306c6e

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b216b27a5b41'
down_revision = '5e6a03306c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_flags', sa.Column('round_issued', sa.SmallInteger(), nullable=False))
    op.drop_constraint('submitted_flags_unique_1', 'submitted_flags', type_='unique')
    op.create_unique_constraint('submitted_flags_unique_1', 'submitted_flags', ['submitted_by', 'team_id', 'service_id', 'round_issued', 'payload'])
    op.drop_column('submitted_flags', 'expires')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_flags', sa.Column('expires', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('submitted_flags_unique_1', 'submitted_flags', type_='unique')
    op.create_unique_constraint('submitted_flags_unique_1', 'submitted_flags', ['submitted_by', 'team_id', 'service_id', 'expires', 'payload'])
    op.drop_column('submitted_flags', 'round_issued')
    # ### end Alembic commands ###
