"""empty message

Revision ID: b80816ee51bf
Revises: 2f793eb41f0e

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80816ee51bf'
down_revision = '2f793eb41f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checker_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='checker_files_unique_1')
    )
    op.create_table('checker_filesystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package', 'path', name='checker_filesystem_unique_1')
    )
    op.add_column('services', sa.Column('package', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'package')
    op.drop_table('checker_filesystem')
    op.drop_table('checker_files')
    # ### end Alembic commands ###
