"""empty message

Revision ID: bead29c0348f
Revises: c2c1a5d3b062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bead29c0348f'
down_revision = 'c2c1a5d3b062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('checker_enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'checker_enabled')
    # ### end Alembic commands ###
