"""empty message

Revision ID: c2c1a5d3b062
Revises: b80816ee51bf

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c1a5d3b062'
down_revision = 'b80816ee51bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('checker_script_dir', sa.String(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'checker_script_dir')
    # ### end Alembic commands ###
