"""empty message

Revision ID: c84ad4bd6649
Revises: 057792e3ba77

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = 'c84ad4bd6649'
down_revision = '057792e3ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_flags', sa.Column('payload', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submitted_flags', 'payload')
    # ### end Alembic commands ###
