"""firstblood is now integer

Revision ID: ca2c4a596673
Revises: 50067ab5c83d
Create Date: 2025-11-06 18:48:14.099271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca2c4a596673'
down_revision = '50067ab5c83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_flags_is_firstblood'), table_name='submitted_flags')
    op.drop_column('submitted_flags', 'is_firstblood')
    op.add_column('submitted_flags', sa.Column('is_firstblood', sa.SMALLINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_submitted_flags_is_firstblood'), 'submitted_flags', ['is_firstblood'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_flags_is_firstblood'), table_name='submitted_flags')
    op.drop_column('submitted_flags', 'is_firstblood')
    op.add_column('submitted_flags', sa.Column('is_firstblood', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_submitted_flags_is_firstblood'), 'submitted_flags', ['is_firstblood'], unique=False)
    # ### end Alembic commands ###
