"""empty message

Revision ID: ddd894b2c20c
Revises: 2bcc2a3e63ea

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd894b2c20c'
down_revision = '2bcc2a3e63ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('setup_package', sa.String(length=32), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'setup_package')
    # ### end Alembic commands ###
