"""empty message

Revision ID: e50efd6bd399
Revises: 6417a3f49101

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e50efd6bd399'
down_revision = '6417a3f49101'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('team_points', sa.Column('off_points', sa.Float(), nullable=False))
	op.add_column('team_points', sa.Column('def_points', sa.Float(), nullable=False))
	op.alter_column('team_points', 'flag_points', nullable=False, new_column_name='flag_captured_count')
	op.add_column('team_points', sa.Column('flag_stolen_count', sa.Integer(), nullable=False))
	op.alter_column('team_points', 'sla_points', existing_type=sa.Integer, type_=sa.Float, existing_nullable=False)
	op.alter_column('team_rankings', 'points', existing_type=sa.Integer, type_=sa.Float, existing_nullable=False)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	#op.add_column('team_points', sa.Column('flag_points', sa.INTEGER(), autoincrement=False, nullable=False))
	op.drop_column('team_points', 'off_points')
	op.drop_column('team_points', 'def_points')
	op.alter_column('team_points', 'flag_captured_count', nullable=False, new_column_name='flag_points')
	op.drop_column('team_points', 'flag_stolen_count')
	op.alter_column('team_points', 'sla_points', existing_type=sa.Float, type_=sa.Integer, existing_nullable=False)
	# ### end Alembic commands ###
