"""empty message

Revision ID: e94f0d7b3dcc
Revises: f764e8e9fbb1

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94f0d7b3dcc'
down_revision = 'f764e8e9fbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('flags_per_round', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'flags_per_round')
    # ### end Alembic commands ###
