"""empty message

Revision ID: f022f2589997
Revises: e94f0d7b3dcc

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f022f2589997'
down_revision = 'e94f0d7b3dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('affiliation', sa.String(length=128), server_default=sa.text('NULL'), nullable=True))
    op.add_column('teams', sa.Column('logo', sa.String(length=64), server_default=sa.text('NULL'), nullable=True))
    op.add_column('teams', sa.Column('website', sa.String(length=128), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'website')
    op.drop_column('teams', 'logo')
    op.drop_column('teams', 'affiliation')
    # ### end Alembic commands ###
