"""empty message

Revision ID: f764e8e9fbb1
Revises: 7aab1b106d02

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f764e8e9fbb1'
down_revision = '7aab1b106d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_points', sa.Column('sla_delta', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_points', 'sla_delta')
    # ### end Alembic commands ###
