"""empty message

Revision ID: fd06fc8ae2cb
Revises: 0e400cc111e2

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd06fc8ae2cb'
down_revision = '0e400cc111e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('vpn_connected', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('teams', sa.Column('vpn_last_connect', sa.TIMESTAMP(), server_default=sa.text('NULL'), nullable=True))
    op.add_column('teams', sa.Column('vpn_last_disconnect', sa.TIMESTAMP(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'vpn_last_disconnect')
    op.drop_column('teams', 'vpn_last_connect')
    op.drop_column('teams', 'vpn_connected')
    # ### end Alembic commands ###
